### PR TITLE
Delete trailing spaces

### PR DESCRIPTION
**Pull request by mathbunnyru**

### CODE REVIEW

**Comment by mathbunnyru** [comment]
@atomgalaxy @whart222 did you stop the development of this project? :(

**Comment by atomgalaxy** [comment]
You write just as I will have time to get back into it in single digit
weeks. I'm currently in the middle of a move, and my current job is a bit
less strenuous.

G

**Comment by mathbunnyru** [comment]
@atomgalaxy thank you for the answer and good luck with your move and job! =)

**Comment by mathbunnyru** [comment]
@atomgalaxy any chance this will be merged?

**Comment by atomgalaxy** [comment]
Ha! Got me. Sorry for completely forgetting about this.

Let me see what I can do this weekend.

H

**Pull request merged**
